---
title: "Invisible Gorilla Hwachon 2015"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

<!--
Data Read-in
------------

```{r, data}
gorilla <- read.table("../data/gorilla_HC.txt", header = TRUE, sep = "")
names(gorilla) <- c("ID", "Q_1", "Q_2", "Q_3", "satQ_1", "satQ_2", "mbiQ_1", "mbiQ_2", "mbiQ_3", "mbiQ_4", "doorQ_1", "chocolate", "gender")
# load("gorilla.rda")
str(gorilla)
```{r, echo = FALSE}
gorilla$monkey <-factor(gorilla$Q_1, levels = c("가", "나", "다"), labels = c("원숭이-바나나", "원숭이-팬더", "팬더-바나나"))
gorilla$leader<-factor(gorilla$Q_2, levels = c("가", "나"), labels = c("여전히 행복하다", "행복하지 않다"))
gorilla$saucer<-factor(gorilla$Q_3, levels = c("가", "나", "다"), labels = c("맨 위", "중간", "맨 아래"))
gorilla$satQ_2 <- factor(gorilla$satQ_2, labels = c("Yes", "No"))
gorilla$mbiQ_2 <- factor(gorilla$mbiQ_2, labels = c("Yes", "No"))
gorilla$mbiQ_3 <- factor(gorilla$mbiQ_3, labels = c("Yes", "No"))
gorilla$mbiQ_4 <- factor(gorilla$mbiQ_4, labels = c("Yes", "No"))
gorilla$satQ_1.2 <- factor(ifelse(gorilla$satQ_1 == 15, "15", "not 15"))
gorilla$mbiQ_1.2 <- factor(ifelse(gorilla$mbiQ_1 == 16, "16", "not 16"))


```

계산 편의를 위하여 `gorilla`를 검색 목록에 등록하고 소숫점 이하 자릿수 조정.

```{r}
attach(gorilla)
options(digits=2)
```
-->

### 동과 서

```{r, east and west}
kable(t(as.matrix(table(monkey), 1)))
kable(t(as.matrix(table(leader), 1)))
kable(t(as.matrix(table(saucer), 1)))
kable(table(saucer, monkey))
```



### Selective Attention

How many passes? 

```{r, SAT}
kable(t(as.matrix(table(satQ_1))))
kable(t(as.matrix(table(satQ_1.2))))
kable(t(as.matrix(prop.table(table(satQ_1.2)))))
```

Did you see the gorilla?

```{r, SAT gorilla}
kable(t(as.matrix(table(satQ_2))))
kable(t(as.matrix(prop.table(table(satQ_2)))))
```

Selective Attention Test에서 패스 성공횟수 카운트와 고릴라 인지 여부

```{r, cross tab}
kable(addmargins(table("패스성공횟수" = satQ_1.2, "고릴라?" = satQ_2)))
kable(prop.table(table("패스성공횟수" = satQ_1.2, "고릴라?" = satQ_2), margin = 1))
```

### Monkey Business Illusion

How many passes?

```{r, MBI pass}
kable(t(as.matrix(table(mbiQ_1))))
kable(t(as.matrix(table(mbiQ_1.2))))
kable(t(as.matrix(prop.table(table(mbiQ_1.2)))))
```

Did you see the gorilla?

```{r, MBI gorilla}
kable(t(as.matrix(table(mbiQ_2))))
kable(t(as.matrix(prop.table(table(mbiQ_2)))))
```

Curtain color changed?

```{r, MBI curtain color}
kable(t(as.matrix(table(mbiQ_3))))
kable(t(as.matrix(prop.table(table(mbiQ_3)))))
```

One of the black team member left?

```{r, MBI leave}
kable(t(as.matrix(table(mbiQ_4))))
kable(t(as.matrix(prop.table(table(mbiQ_4)))))
```

패스 성공횟수 카운트와 고릴라 인지 여부, 커튼색깔 변화 인지 여부, 선수퇴장 인지 여부.

```{r, MBI}
kable(addmargins(table("패스성공횟수" = mbiQ_1.2, "고릴라?" = mbiQ_2)))
kable(prop.table(table("패스성공횟수" = mbiQ_1.2, "고릴라?" = mbiQ_2), margin = 1))
kable(addmargins(table("패스성공횟수" = mbiQ_1.2, "커튼 색깔이?" = mbiQ_3)))
kable(prop.table(table("패스성공횟수" = mbiQ_1.2, "커튼 색깔이?" = mbiQ_3), margin = 1))
kable(addmargins(table("패스성공횟수" = mbiQ_1.2, "선수 퇴장?" = mbiQ_4)))
kable(prop.table(table("패스성공횟수" = mbiQ_1.2, "선수 퇴장?" = mbiQ_4), margin = 1))
```

### Save

```{r, save}
save.image(file = "./gorilla_1402.RData")
```
